"use client";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "../components/ui/Button";
import type { IntakeRecord } from "@/lib/services/intakes";

const statusLabel=(s:IntakeRecord["status"])=>s.replace("_"," ").toUpperCase();
export function IntakesPage({initialIntakes}:{initialIntakes:IntakeRecord[]}){
 const [filter,setFilter]=useState("ALL");
 const filtered=useMemo(()=>initialIntakes.filter(i=>filter==="ALL"?true:filter==="OPEN"?["open","closing_soon","active"].includes(i.status):i.status==="upcoming"),[initialIntakes,filter]);
 const featured=initialIntakes[0]??null;
 const fmt=(d:string|null)=>d?new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${d}T00:00:00`)):"Date TBA";
 return <div className="w-full bg-[var(--color-background)] min-h-screen">
  <section className="pt-32 pb-16 lg:pt-48 lg:pb-24 bg-[var(--color-surface)] border-b border-[var(--color-border)]"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold text-[var(--color-accent)] uppercase tracking-widest mb-6">Upcoming Intakes</p><h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight text-[var(--color-text-primary)] leading-[1.1] mb-8">Your Next Opportunity <span className="text-[var(--color-accent)]">Starts Here.</span></h1><p className="text-xl text-[var(--color-text-secondary)] leading-relaxed">Find confirmed Nenasala programme intakes and registration windows directly from our live schedule.</p></div></div></section>
  {featured&&<section className="py-12"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="bg-[var(--color-primary)] rounded-[var(--radius-xl)] p-8 sm:p-12 text-[var(--color-static-white)] flex flex-col md:flex-row justify-between gap-8"><div><p className="text-sm font-bold uppercase tracking-widest opacity-80 mb-3">Next Intake</p><h2 className="text-3xl sm:text-4xl font-extrabold">{featured.programme_name}</h2><p className="mt-3 opacity-90">{featured.name} • {fmt(featured.start_date)}</p><div className="mt-7 flex gap-3"><Link to="/courses"><Button className="rounded-full bg-[var(--color-static-white)] text-[var(--color-primary)]">Explore Courses</Button></Link></div></div><div className="self-start rounded-[var(--radius-lg)] border border-white/20 bg-white/10 px-6 py-5"><div className="text-sm uppercase tracking-widest opacity-80">Status</div><div className="mt-1 text-xl font-bold">{statusLabel(featured.status)}</div></div></div></div></section>}
  <section className="py-12 lg:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap gap-2 mb-10">{["ALL","OPEN","UPCOMING"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-6 py-2.5 rounded-full text-sm font-bold ${filter===f?"bg-[var(--color-primary)] text-white":"bg-[var(--color-surface)] border border-[var(--color-border)]"}`}>{f}</button>)}</div><div className="space-y-4">{filtered.length?filtered.map(i=><motion.div key={i.id} initial={{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="bg-[var(--color-surface)] border border-[var(--color-border)] rounded-[var(--radius-lg)] p-6 flex flex-col md:flex-row md:items-center gap-5"><div className="md:w-40"><div className="font-extrabold text-xl text-[var(--color-text-primary)]">{fmt(i.start_date)}</div></div><div className="flex-1"><h3 className="text-xl font-bold text-[var(--color-text-primary)]">{i.programme_name}</h3><p className="text-[var(--color-text-secondary)]">{i.name}</p></div><span className="text-xs font-bold uppercase tracking-wider rounded-full px-3 py-1 bg-[var(--color-surface-muted)]">{statusLabel(i.status)}</span><Link to="/courses" className="text-[var(--color-primary)] font-semibold">Details →</Link></motion.div>):<div className="text-center py-20 bg-[var(--color-surface)] border border-[var(--color-border)] rounded-[var(--radius-xl)]"><h3 className="text-2xl font-bold mb-2">No confirmed intakes yet.</h3><p className="text-[var(--color-text-secondary)]">New dates will appear here as soon as Nenasala publishes them.</p></div>}</div></div></section>
 </div>;
}
