"use client";

import { useMemo, useState } from "react";
import { Download, ExternalLink, FileText, FolderOpen, Image as ImageIcon, Link2 } from "lucide-react";
import type { CourseMaterialRecord, TeachingCourse } from "@/lib/services/instructor-teaching";

export default function StudentMaterials({ courses, materials }: { courses: TeachingCourse[]; materials: CourseMaterialRecord[] }) {
  const [courseId,setCourseId]=useState(courses[0]?.id??"");
  const visible=useMemo(()=>materials.filter((row)=>row.course_id===courseId),[materials,courseId]);
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight text-[var(--color-text-primary)]">Course Materials</h1><p className="mt-1 text-[var(--color-text-secondary)]">Select a course to view and download files shared by your instructor.</p></div>
    {courses.length===0?<Empty/>:<><div className="max-w-md"><label className="mb-1.5 block text-sm font-semibold text-[var(--color-text-primary)]">Course</label><select value={courseId} onChange={(e)=>setCourseId(e.target.value)} className="h-11 w-full rounded-[var(--radius-sm)] border border-[var(--color-border)] bg-[var(--color-surface)] px-3 text-sm text-[var(--color-text-primary)] outline-none focus:ring-1 focus:ring-[var(--color-primary)]">{courses.map((course)=><option key={course.id} value={course.id}>{course.title}</option>)}</select></div>{visible.length===0?<Empty text="No materials have been published for this course yet."/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((material)=>{const Icon=material.file_kind==="image"?ImageIcon:material.material_type==="link"?Link2:FileText;return <article key={material.id} className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-1 shadow-sm"><div className="h-full rounded-[calc(var(--radius-lg)-4px)] bg-[var(--color-surface-elevated)] p-5"><span className="grid h-11 w-11 place-items-center rounded-[var(--radius-md)] bg-[var(--color-primary-soft)] text-[var(--color-primary)]"><Icon className="h-5 w-5"/></span><h2 className="mt-4 font-bold text-[var(--color-text-primary)]">{material.title}</h2>{material.description&&<p className="mt-2 text-sm leading-6 text-[var(--color-text-secondary)]">{material.description}</p>}<p className="mt-3 text-xs capitalize text-[var(--color-text-muted)]">{material.file_kind}{material.file_name?` · ${material.file_name}`:""}</p><div className="mt-5 flex flex-wrap gap-2">{material.material_type==="link"&&material.view_url?<a href={material.view_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-4 py-2 text-sm font-bold text-white"><ExternalLink className="h-4 w-4"/>Open link</a>:<>{material.view_url&&<a href={material.view_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-[var(--radius-sm)] border border-[var(--color-border)] px-4 py-2 text-sm font-bold text-[var(--color-text-primary)] hover:bg-[var(--color-surface)]">Preview</a>}{material.download_url&&<a href={material.download_url} className="inline-flex items-center gap-2 rounded-[var(--radius-sm)] bg-[var(--color-primary)] px-4 py-2 text-sm font-bold text-white"><Download className="h-4 w-4"/>Download</a>}</>}</div></div></article>})}</div>}</>}
  </div>;
}
function Empty({text="You do not have any course materials yet."}:{text?:string}){return <div className="rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-10 text-center"><FolderOpen className="mx-auto h-8 w-8 text-[var(--color-text-muted)]"/><p className="mt-3 text-sm text-[var(--color-text-secondary)]">{text}</p></div>}
